services:
  appseed-app:
    restart: always
    build: .
    networks:
      - db_network
      - web_network
    expose:
      - "8000" 
    deploy:
      replicas: 3
      mode: replicated

  nginx:
    image: "nginx:latest"
    ports:
      - "5085:5085"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks:
      - web_network
    depends_on: 
      - appseed-app

networks:
  db_network:
    driver: bridge
  web_network:
    driver: bridge